### ISSUE TITLE
求助 ask for help

### ISSUE THREAD

**Issue by jianing999** [TensorStrike/soybean_fedpruning#1]
大佬您好，可否求一份数据集？我自己用了一周时间了都没下载到数据集，由于英语水平有限看不太懂数据集的描述文件，不知道该怎么获得，只能在这里寻求帮助了，万分感谢！

Hello, senior, can you ask for a data set? I haven't downloaded the data set since I used it for a week. Because of my limited English level, I don't quite understand the description file of the data set. I don't know how to get it, so I can only ask for help here. Thank you very much!

**Comment by jianing999** [comment]
期待您的回复，不知道我又没有这个荣幸得到您的帮助，但我内心依然燃烧着希望。
Looking forward to your reply, I don't know that I don't have the honor to get your help, but my heart is still burning with hope.

**Comment by jianing999** [comment]
不知您何时能看到我的求助，但我会一直等待着。
I don't know when you can see my help, but I will always wait.

**Comment by jianing999** [comment]
前辈什么时候可以看到我的消息啊，坐等
When can the seniors see my news? Just wait.

**Comment by jianing999** [comment]
最近天天再努力，但仍不见显著效果，还望得到前辈的指导
I have been working hard every day recently, but I still have no obvious effect. I still hope to get guidance from my predecessors.

**Comment by jianing999** [comment]
Wow, I have received your email. I love you so much. A good day begins with seeing your email.

**Comment by lei330326** [comment]
Hello, I also hope to obtain a dataset. Can you help me? Thank you very much

**Comment by jianing999** [comment]
> Hello, I also hope to obtain a dataset. Can you help me? Thank you very much

Hello,I'm very sorry to hear from you so late. I want to ask how big the data set you found is. Is the soybean_samples.csv file 1500 lines? I feel that my file is incomplete. I have to modify the Soybeans_Loc_ID.cvs file before I can run the experiment. Do you have the same problem? Maybe we can exchange each other's data sets and make progress together. If you don't read this page often, you can call: 19831602510 to synchronize WeChat.

**Comment by jianing999** [comment]
> Hello, I also hope to obtain a dataset. Can you help me? Thank you very much

Commonly used mailboxes are 32209196@mail.imu.edu.cn

**Comment by jianing999** [comment]
It's solved. Excuse me.
