### ISSUE TITLE
ask for obtaining a dataset

### ISSUE THREAD

**Issue by lei330326** [TensorStrike/soybean_fedpruning#2]
Hello, I hope this message finds you well. I was wondering if it would be possible for me to obtain a copy of the dataset? Your assistance in this matter would be greatly appreciated. Looking forward to hearing from you soon.

**Comment by lei330326** [comment]
Oh, I found it. Sorry to have bothered you.

**Comment by jianing999** [comment]
Hello,I'm very sorry to hear from you so late. I want to ask how big the data set you found is. Is the soybean_samples.csv file 1500 lines? I feel that my file is incomplete. I have to modify the Soybeans_Loc_ID.cvs file before I can run the experiment. Do you have the same problem? Maybe we can exchange each other's data sets and make progress together. If you don't read this page often, you can call: 19831602510 to synchronize WeChat

**Comment by jianing999** [comment]
Commonly used mailboxes are  32209196 mail.imu.edu.cn

**Comment by jianing999** [comment]
Commonly used mailboxes are 32209196@mail.imu.edu.cn
